### ISSUE TITLE
Ninja failed with exited code (1)

### ISSUE THREAD

**Issue by farhanjaa** [joachimBurket/esp32-opencv#5]
hi JoachimBurket, Thank you for your insight and everything usefull library related to openCV. I had followed all oh your instruction but i've always had problem like this
../main/report.cpp: In member function 'void TestCase::executeOn(const imagesList&)':
../main/report.cpp:23:32: error: exception handling disabled, use -fexceptions to enable
         } catch(cv::Exception& e) {
                                ^
../main/report.cpp:24:119: error: 'e' was not declared in this scope
             cout << "Exception while trying to execute function " << name << " on image " << get<0>(img) << " :\n" << e.msg;
                                                                                                                       ^
ninja: build stopped: subcommand failed.
ninja failed with exit code 1
Can you help me abt this?

**Comment by joachimBurket** [comment]
Hi,
Sorry for the delay, I'm currently working on other projects.
Glad this project can help! :)

Could you give me more information on the version of esp-idf you're using, which project you are trying to run, and if you are using the pre-compiled opencv in the project?
